# Generated by Django 5.0.4 on 2024-07-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_reporte',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_solicitud',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identidad', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'tipo_rol',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionsolicitud.persona')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionsolicitud.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_incidente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('detalles', models.TextField()),
                ('policia_notificado', models.CharField(max_length=50)),
                ('causas', models.CharField(blank=True, max_length=255, null=True)),
                ('recomendaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('recibido_por', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_seguimiento', models.CharField(editable=False, max_length=12, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionsolicitud.estadoreporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMesaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('descripcion_solicitud', models.TextField()),
                ('nombres_administrador', models.CharField(max_length=255)),
                ('nombres_representante', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_tercero_representante', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio_procesal', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio_real', models.CharField(max_length=255)),
                ('numero_documento', models.CharField(max_length=20)),
                ('numero_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_recibo', models.DateField(blank=True, null=True)),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fundamento_solicitud', models.TextField()),
                ('descripcion_documento', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes_adjuntos/')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionsolicitud.estadosolicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_identificacion_administrador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_identificacion_administrador', to='gestionsolicitud.tipoidentificacion')),
                ('tipo_identificacion_representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_identificacion_representante', to='gestionsolicitud.tipoidentificacion')),
                ('tipo_identificacion_tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tipo_identificacion_tercero', to='gestionsolicitud.tipoidentificacion')),
            ],
            options={
                'db_table': 'solicitud_mesaparte',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionsolicitud.tipoidentificacion'),
        ),
    ]
